scrumptious/urls.py
from django.contrib.auth import views as auth_views
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("recipes/", include("recipes.urls")),
    path("tags/", include("tags.urls")),
    path("meal_plans/", include("meal_plans.urls")),
    path("accounts/login/", auth_views.LoginView.as_view(), name="login"),
    path("accounts/logout/", auth_views.LogoutView.as_view(), name="logout"),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("recipes_list")),
        name="home",
    ),
]

tags/urls.py
from django.urls import path

from tags.views import (
    # show_tags,
    TagListView,
    TagDetailView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView,
)


urlpatterns = [
    # path("", show_tags, name="tags_list"),
    path("", TagListView.as_view(), name="tags_list"),
    path("<int:pk>/", TagDetailView.as_view(), name="tag_detail"),
    path("new/", TagCreateView.as_view(), name="tag_new"),
    path("<int:pk>/update/", TagUpdateView.as_view(), name="tag_edit"),
    path("<int:pk>delete/", TagDeleteView.as_view(), name="tag_delete"),
]

tags/models.py
from django.db import models
from django.conf import settings

USER_MODEL = settings.AUTH_USER_MODEL

# Create your models here.
class Tag(models.Model):
    name = models.CharField(max_length=20)
    recipes = models.ManyToManyField("recipes.Recipe", related_name="tags")
    author = models.ForeignKey(
        USER_MODEL, related_name="tags", on_delete=models.CASCADE, null=True
    )

    def __str__(self):
        return self.name

tags/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin

from recipes.models import Recipe
from tags.models import Tag

# Tag = None


class TagListView(ListView):
    model = Tag
    template_name = "tags/list.html"
    context_object_name = "tags"


class TagDetailView(DetailView):
    model = Tag
    context_object_name = "tag"
    template_name = "tags/detail.html"


class TagCreateView(LoginRequiredMixin, CreateView):
    model = Tag
    template_name = "tags/create.html"
    sucess_url = "/"


class TagUpdateView(LoginRequiredMixin, UpdateView):
    model = Recipe
    template_name = "tags/edit.html"


class TagDeleteView(LoginRequiredMixin, DeleteView):
    model = Tag
    template_name = "tags/delete.html"


def show_tags(request):
    context = {
        "tags": Tag.objects.all() if Tag else None,
    }
    return render(request, "tags/list.html", context)

tags/templates/tags/create.html
{% extends 'base.html' %} {% load static %} {% load markdownify %}
<div></div>
{% block content %}
<main class="recipe-form">
  <form method="post">
    {% csrf_token %} {{ form.as_p }}
    <div class="control">
      <button class="button">Create</button>
    </div>
  </form>
</main>
{% endblock content %}

tags/templates/tags/delete.html
{% extends 'base.html' %} {% load static %} {% load markdownify %}
<div></div>
{% block content %}
<main>
  <div class="delete-form">
    <form method="post">
      {% csrf_token %}
      <h3>Are you sure you want to delete "{{ tag.name }}"?</h3>
      {{ form.as_p }}
      <div>
        <button class="button">Delete</button>
      </div>
    </form>
  </div>
</main>
{% endblock content %}

tags/templates/tags/detail.html
{% extends 'base.html' %} {% load static %} {% load markdownify %}
<div></div>
{% block content %}
<main class="tag-detail">
  <div>
    <a href="{% url 'tag_edit' tag.id %}">Edit</a>
    <a href="{% url 'tag_delete' tag.id %}">Delete</a>
  </div>
  <h2>Recipes for {{ tag.name }}</h2>
  {% for recipe in mealplan.recipes.all %}
  <p>
    <a href="{% url 'recipe_detail' recipe.pk %}">{{ recipe.name }}</a>
  </p>
  {% endfor %}
</main>
{% endblock content %}

tags/templates/tags/edit.html
{% extends 'base.html' %} {% load static %} {% load markdownify %}
<div></div>
{% block content %}
<main class="recipe-form">
  <form method="post">
    {% csrf_token %} {{ form.as_p }}
    <div class="control">
      <button class="button">Update</button>
    </div>
  </form>
</main>
{% endblock content %}

tags/templates/tags/list.html
{% load static %} {% load markdownify %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Tags - Scrumptious</title>
    <link rel="stylesheet" href="{% static 'css/app.css' %}" />
  </head>

  <body>
    <header>
      <nav>
        <ul>
          <li>
            <a href="{% url 'home' %}">Scrumptious</a>
          </li>
          <li>
            <a href="{% url 'tags_list' %}">Tags</a>
          </li>
          <li>
            <a href="{% url 'admin:index' %}">Admin</a>
          </li>
          <li>
            <a href="{% url 'recipe_new' %}">Write a recipe</a>
          </li>
        </ul>
      </nav>
      <div class="pagination">
        <span class="step-links">
          {% if page_obj.has_previous %}
          <a href="?page=1">&laquo; first</a>
          <a href="?page={{ page_obj.previous_page_number }}">previous</a>
          {% endif %}

          <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
          </span>

          {% if page_obj.has_next %}
          <a href="?page={{ page_obj.next_page_number }}">next</a>
          <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
          {% endif %}
        </span>
      </div>
    </header>
    <main class="recipe-grid">
      {% for tag in tag_list %}
      <div class="recipe-card">
        <h2 class="recipe-card-title">
          <a href="{% url 'tag_detail' tag.id %}">{{ tag.name }}</a>
        </h2>
        {% for recipe in tag.recipes.all %}
        <p>
          <a href="{% url 'recipe_detail' recipe.pk %}">{{ recipe.name }}</a>
        </p>
        {% endfor %}
      </div>
      {% empty %}
      <div>
        <h1>No tags, yet</h1>
        <p>
          Would you like to
          <a href="{% url 'tag_new' %}">create</a>
          one?
        </p>
      </div>
      {% endfor %}
    </main>
  </body>
</html>